### ISSUE TITLE
failing torrentsites

### ISSUE THREAD

**Issue by Frydac** [kryptxy/torrench#89]
Hi,

I was trying out your application, and while some of the torrent sites worked, not all. I thought I'd share my findings:
I built torrench from source, from commit 2c4869e
my config.ini updated with `torrench -U`:
```
[Torrench-Config]
tpb_url = https://thepiratebay.org  https://proxybay.one
sky_url = https://www.skytorrents.in
kat_url = https://kickass.cd/ https://kickass.unblocked.bid/ https://kickass.unlockproj.faith/
nyaa_url = https://nyaa.si/
xbit_url = https://xbit.pw/
rarbg_url = https://torrentapi.org/pubapi_v2.php?
1337x_url = https://1337x.to https://1337x.unblockall.org https://proxyportal.net/1337x-proxy
idope_url = https://idope.se
libgen_url = http://libgen.io/
limetorrents_url = https://limetorrents.cc https://swaptorrents.com
enable = 1
```

Then I tried following bash script, and I commented out the ones that where working for me:
```
#!/bin/bash

# torrench -t Simpsons # working
torrench -k Simpsons
torrench -s Simpsons
torrench -x Simpsons
# torrench -r Simpsons # working
torrench -l Simpsons
torrench -i Simpsons
torrench -b Simpsons
torrench -g 0321714121
```

the output:

```
▶ ./test_torrench.sh

[KickassTorrents]

Obtaining proxies...
Trying https://kickass.cd/
Traceback (most recent call last):
  File "/usr/bin/torrench", line 11, in <module>
    load_entry_point('torrench==1.0.61', 'console_scripts', 'torrench')()
  File "/usr/lib/python3.7/site-packages/torrench-1.0.61-py3.7.egg/torrench/__main__.py", line 28, in main
    Torrench.main()
  File "/usr/lib/python3.7/site-packages/torrench-1.0.61-py3.7.egg/torrench/Torrench.py", line 340, in main
    tr.resolve_args()
  File "/usr/lib/python3.7/site-packages/torrench-1.0.61-py3.7.egg/torrench/Torrench.py", line 254, in resolve_args
    kat.main(self.input_title, self.page_limit)
  File "/usr/lib/python3.7/site-packages/torrench-1.0.61-py3.7.egg/torrench/modules/kickasstorrent.py", line 155, in main
    kat.check_proxy()
  File "/usr/lib/python3.7/site-packages/torrench-1.0.61-py3.7.egg/torrench/modules/kickasstorrent.py", line 67, in check_proxy
    if self.soup.find('a')['href'] != proxy + "/full/" or self.soup == -1:
AttributeError: 'int' object has no attribute 'find'

[SkyTorrents]

Obtaining proxies...
Trying https://www.skytorrents.in
Error message: 'int' object has no attribute 'find_all'
Something went wrong! See logs for details. Exiting!

[1337x]

Obtaining proxies...
Traceback (most recent call last):
  File "/usr/bin/torrench", line 11, in <module>
    load_entry_point('torrench==1.0.61', 'console_scripts', 'torrench')()
  File "/usr/lib/python3.7/site-packages/torrench-1.0.61-py3.7.egg/torrench/__main__.py", line 28, in main
    Torrench.main()
  File "/usr/lib/python3.7/site-packages/torrench-1.0.61-py3.7.egg/torrench/Torrench.py", line 340, in main
    tr.resolve_args()
  File "/usr/lib/python3.7/site-packages/torrench-1.0.61-py3.7.egg/torrench/Torrench.py", line 282, in resolve_args
    x13.main(self.input_title, self.page_limit)
  File "/usr/lib/python3.7/site-packages/torrench-1.0.61-py3.7.egg/torrench/modules/x1337.py", line 186, in main
    x13 = x1337(title, page_limit)
  File "/usr/lib/python3.7/site-packages/torrench-1.0.61-py3.7.egg/torrench/modules/x1337.py", line 32, in __init__
    self.proxies = self.get_proxies('1337x')
  File "/usr/lib/python3.7/site-packages/torrench-1.0.61-py3.7.egg/torrench/utilities/Config.py", line 100, in get_proxies
    link = soup.findAll('td', class_='text-left')
AttributeError: 'int' object has no attribute 'findAll'

[LimeTorrents]

Obtaining proxies...
Trying https://limetorrents.cc
Bad proxy!

Trying https://swaptorrents.com
Bad proxy!

No more proxies found! Terminating

[Idope]

Fetching from page: 1
Error message: cannot unpack non-iterable int object
Something went wrong! See logs for details. Exiting!

[XBit.pw]

Using https://xbit.pw/
Fetching results...
Error message: Expecting value: line 1 column 1 (char 0)
Something went wrong! See logs for details. Exiting!

[LibGen]

Error message: Expecting value: line 1 column 1 (char 0)
Something went wrong! See logs for details. Exiting!
```
I guess the limetorrents mirrors are not working here, but otherwise, most sites seem to work (or at least the ones I tried).

Now, I would get 95% of what I need from (the for me working) tpb or rarbg anyway, didn't even know about some of the others. And I don't mind using the libgen site itself, it doesn't have an onslaught of adware like most of the others.
